<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:py="http://genshi.edgewall.org/"
      xmlns:xi="http://www.w3.org/2001/XInclude">
<py:def function="page_title">Image Error</py:def>
<py:def function="head_info">
    <link rel="stylesheet" type="text/css" href="${tg.url('/static/css/error.css')}" />
</py:def>
<py:def function="page_parents"></py:def>

<py:match path="content">
    <p>The server has reported an error for the image you have just tried to use.  The error is:</p>
    <div id="error">
        <p class="error_name" py:content="type(error).__name__">[error name]</p>
        <p py:content="error">[error]</p>
    </div>
    <a id="back_link" href="#">Back</a>
    <script type="text/javascript">
        // EVENTS //
        safe_connect('back_link', 'onclick',
            function(event)
            {
                history.back();
                event.stop();
            });
    </script>
</py:match>

<xi:include href="master.html" />

</html>
